// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.0--rc1
// source: greeter.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 接口的请求参数类型
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Var1  string `protobuf:"bytes,1,opt,name=var1,proto3" json:"var1,omitempty"`
	Var2  string `protobuf:"bytes,2,opt,name=var2,proto3" json:"var2,omitempty"`
	Var3  string `protobuf:"bytes,3,opt,name=var3,proto3" json:"var3,omitempty"`
	Var4  string `protobuf:"bytes,4,opt,name=var4,proto3" json:"var4,omitempty"`
	Var5  string `protobuf:"bytes,5,opt,name=var5,proto3" json:"var5,omitempty"`
	Var6  string `protobuf:"bytes,6,opt,name=var6,proto3" json:"var6,omitempty"`
	Var7  string `protobuf:"bytes,7,opt,name=var7,proto3" json:"var7,omitempty"`
	Var8  string `protobuf:"bytes,8,opt,name=var8,proto3" json:"var8,omitempty"`
	Var9  string `protobuf:"bytes,9,opt,name=var9,proto3" json:"var9,omitempty"`
	Var10 string `protobuf:"bytes,10,opt,name=var10,proto3" json:"var10,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetVar1() string {
	if x != nil {
		return x.Var1
	}
	return ""
}

func (x *HelloRequest) GetVar2() string {
	if x != nil {
		return x.Var2
	}
	return ""
}

func (x *HelloRequest) GetVar3() string {
	if x != nil {
		return x.Var3
	}
	return ""
}

func (x *HelloRequest) GetVar4() string {
	if x != nil {
		return x.Var4
	}
	return ""
}

func (x *HelloRequest) GetVar5() string {
	if x != nil {
		return x.Var5
	}
	return ""
}

func (x *HelloRequest) GetVar6() string {
	if x != nil {
		return x.Var6
	}
	return ""
}

func (x *HelloRequest) GetVar7() string {
	if x != nil {
		return x.Var7
	}
	return ""
}

func (x *HelloRequest) GetVar8() string {
	if x != nil {
		return x.Var8
	}
	return ""
}

func (x *HelloRequest) GetVar9() string {
	if x != nil {
		return x.Var9
	}
	return ""
}

func (x *HelloRequest) GetVar10() string {
	if x != nil {
		return x.Var10
	}
	return ""
}

// 接口的响应参数类型
type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rpy1  string `protobuf:"bytes,1,opt,name=rpy1,proto3" json:"rpy1,omitempty"`
	Rpy2  string `protobuf:"bytes,2,opt,name=rpy2,proto3" json:"rpy2,omitempty"`
	Rpy3  string `protobuf:"bytes,3,opt,name=rpy3,proto3" json:"rpy3,omitempty"`
	Rpy4  string `protobuf:"bytes,4,opt,name=rpy4,proto3" json:"rpy4,omitempty"`
	Rpy5  string `protobuf:"bytes,5,opt,name=rpy5,proto3" json:"rpy5,omitempty"`
	Rpy6  string `protobuf:"bytes,6,opt,name=rpy6,proto3" json:"rpy6,omitempty"`
	Rpy7  string `protobuf:"bytes,7,opt,name=rpy7,proto3" json:"rpy7,omitempty"`
	Rpy8  string `protobuf:"bytes,8,opt,name=rpy8,proto3" json:"rpy8,omitempty"`
	Rpy9  string `protobuf:"bytes,9,opt,name=rpy9,proto3" json:"rpy9,omitempty"`
	Rpy10 string `protobuf:"bytes,10,opt,name=rpy10,proto3" json:"rpy10,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetRpy1() string {
	if x != nil {
		return x.Rpy1
	}
	return ""
}

func (x *HelloReply) GetRpy2() string {
	if x != nil {
		return x.Rpy2
	}
	return ""
}

func (x *HelloReply) GetRpy3() string {
	if x != nil {
		return x.Rpy3
	}
	return ""
}

func (x *HelloReply) GetRpy4() string {
	if x != nil {
		return x.Rpy4
	}
	return ""
}

func (x *HelloReply) GetRpy5() string {
	if x != nil {
		return x.Rpy5
	}
	return ""
}

func (x *HelloReply) GetRpy6() string {
	if x != nil {
		return x.Rpy6
	}
	return ""
}

func (x *HelloReply) GetRpy7() string {
	if x != nil {
		return x.Rpy7
	}
	return ""
}

func (x *HelloReply) GetRpy8() string {
	if x != nil {
		return x.Rpy8
	}
	return ""
}

func (x *HelloReply) GetRpy9() string {
	if x != nil {
		return x.Rpy9
	}
	return ""
}

func (x *HelloReply) GetRpy10() string {
	if x != nil {
		return x.Rpy10
	}
	return ""
}

var File_greeter_proto protoreflect.FileDescriptor

var file_greeter_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd8, 0x01, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x72, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x76,
	0x61, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x72, 0x32, 0x12,
	0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76,
	0x61, 0x72, 0x33, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x76, 0x61, 0x72, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x35, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x72, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x76,
	0x61, 0x72, 0x36, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x72, 0x36, 0x12,
	0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x37, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76,
	0x61, 0x72, 0x37, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x38, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x76, 0x61, 0x72, 0x38, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x39, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x72, 0x39, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x72, 0x31, 0x30, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x72, 0x31,
	0x30, 0x22, 0xd6, 0x01, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x70, 0x79, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x70, 0x79, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x70, 0x79, 0x32, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x70, 0x79, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x70, 0x79, 0x33,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x70, 0x79, 0x33, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x70, 0x79, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x70, 0x79, 0x34,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x70, 0x79, 0x35, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x70, 0x79, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x70, 0x79, 0x36, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x70, 0x79, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x70, 0x79, 0x37,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x70, 0x79, 0x37, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x70, 0x79, 0x38, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x70, 0x79, 0x38,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x70, 0x79, 0x39, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x70, 0x79, 0x39, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x70, 0x79, 0x31, 0x30, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x70, 0x79, 0x31, 0x30, 0x32, 0x44, 0x0a, 0x0c, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x53, 0x61,
	0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x12, 0x0a, 0x0d, 0x6f, 0x72, 0x67, 0x2e, 0x79, 0x6d, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5a, 0x01, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_greeter_proto_rawDescOnce sync.Once
	file_greeter_proto_rawDescData = file_greeter_proto_rawDesc
)

func file_greeter_proto_rawDescGZIP() []byte {
	file_greeter_proto_rawDescOnce.Do(func() {
		file_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(file_greeter_proto_rawDescData)
	})
	return file_greeter_proto_rawDescData
}

var file_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_greeter_proto_goTypes = []interface{}{
	(*HelloRequest)(nil), // 0: proto.HelloRequest
	(*HelloReply)(nil),   // 1: proto.HelloReply
}
var file_greeter_proto_depIdxs = []int32{
	0, // 0: proto.HelloService.SayHello:input_type -> proto.HelloRequest
	1, // 1: proto.HelloService.SayHello:output_type -> proto.HelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greeter_proto_init() }
func file_greeter_proto_init() {
	if File_greeter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_greeter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_greeter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greeter_proto_goTypes,
		DependencyIndexes: file_greeter_proto_depIdxs,
		MessageInfos:      file_greeter_proto_msgTypes,
	}.Build()
	File_greeter_proto = out.File
	file_greeter_proto_rawDesc = nil
	file_greeter_proto_goTypes = nil
	file_greeter_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	// 接口的具体方法
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type helloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloServiceClient(cc grpc.ClientConnInterface) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/proto.HelloService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	// 接口的具体方法
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HelloService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}
